title: hll app
description: hll app
theme: just-the-docs

port: 4006

url: https://github.com/hell-gun-calculator
favicon_ico: "/assets/images/logo.png"
logo: "/assets/images/logo-docs.png"
search_enabled: true

callouts:
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: HLL-Gun-Calc Web版
    url: https://hll-web-app.cabbagelol.net
