title: hll app
description: hll-gun-calc
theme: just-the-docs
port: 4000
url: https://github.com/hell-gun-calculator
favicon_ico: "/assets/images/logo.png"
logo: "/assets/images/logo-docs.png"
search_enabled: true
color_scheme: hll

collections:
  tests:
    permalink: "/:collection/:path/"
    output: true

callouts:
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: HLL-Gun-Calc Web版
    url: https://hll-gun-calculato-app-for-web.vercel.app/
